FluxML/Optimisers.jl

.github/workflows/CompatHelper.yml
.github/workflows/TagBot.yml
Manifest.toml
Project.toml
src/Optimisers.jl
src/interface.jl
src/rules.jl
test/runtests.jl

Add some more Optimisers

---

src/rules.jl
test/runtests.jl

We have spoken about having a simple way to do this.

Add optimiser updates utility

---

src/interface.jl
src/rules.jl
test/runtests.jl

Closes https://github.com/FluxML/Optimisers.jl/issues/28

Optimise only at `isnumeric` leaves

---

docs/src/index.md

Minor tweaks, some semicolons so that it doesn't print huge things. Ideally would be run during testing, but maybe later...
Closes #26

Make the example run

---

src/rules.jl
test/runtests.jl

Previously, using one or no arguments gave something which gave an error about iterating Descent. Now it should just work.

Trivial cases of `OptimiserChain`

---

Project.toml
src/Optimisers.jl
src/destructure.jl
test/destructure.jl

Allow destructure to make an empty vector

---

src/rules.jl

Cf https://github.com/FluxML/Flux.jl/pull/1963
CC @mcabbott @darsnack

AdaBelief bias correction and epsilon

---

README.md
docs/src/index.md

Xref https://github.com/FluxML/Optimisers.jl/issues/76

Document the need for explicit gradients

---

Project.toml
docs/src/index.md
src/Optimisers.jl
src/interface.jl
src/rules.jl

Required for https://github.com/SciML/GalacticOptim.jl/pull/255

Put an abstract type over the optimisers to allow dispatch

---

.github/workflows/ci.yml
docs/Project.toml
docs/make.jl
src/Optimisers.jl

- adds colored output to GitHub Actions to diagnose failures easily
- doctests now run only once
- fixes some broken doctests
- adds the dependencies required to run doctests

Fix the doctests and the broken CI

---

src/Optimisers.jl
src/rules.jl
test/rules.jl

https://ieeexplore.ieee.org/document/298623
https://pytorch.org/docs/stable/generated/torch.optim.Rprop.html#torch.optim.Rprop

Implement Rprop

---

src/rules.jl
test/runtests.jl

Now the type of states is always the same as the of parameters

fix type instability of `Rprop`

---

docs/src/assets/flux.css

Matches Flux after changes in https://github.com/FluxML/Flux.jl/pull/2069
Should ideally move to https://github.com/FluxML/.github perhaps?

Remove negative space from css

---

.github/workflows/ci.yml

update: actions node 12 => node 16

---

src/Optimisers.jl
src/destructure.jl

fix anonymous walk deprecation

---

Project.toml
docs/src/api.md

Resolves https://github.com/FluxML/Optimisers.jl/issues/156#issuecomment-1685033755.
- N/A Tests are added

Add Lion to docs

---

src/rules.jl

Fix Float64 beta in Adam etc.

---

docs/src/index.md
src/interface.jl

Add some documentation for #143 and #140

docs for nothing behavior and for walking a tree with keypath

---

Project.toml
ext/OptimisersReactantExt.jl
src/utils.jl

Alternate for https://github.com/FluxML/Optimisers.jl/pull/206
@mcabbott @CarloLucibello

Prevent recursion in _eps

---

Project.toml

IDK why compathelper hasn't made a PR, it is running
Needed for https://github.com/FluxML/Flux.jl/pull/2574

Allow Zygote 0.7
