FluxML/Optimisers.jl

src/Optimisers.jl
src/interface.jl
src/rules.jl
test/runtests.jl

This PR finishes the already good work in this repo to move all the optimizers from Flux to Optimisers.jl. The main advantage of the implementation in Optimisers.jl is the use of functors and explicit state. This eliminates the need for any `IdDict`s and simplifies how compositions of basic optimizers work.
~~One notable exception: this implementation is mutable. The simple reason for this is that immutable updates will copy entire models and result in high memory usage. Until we have a compiler optimization to address this, this PR opts to have mutable updates for now. You can read more about the reasoning [in this design note](https://github.com/FluxML/ML-Coordination-Tracker/discussions/22).~~
Remaining tasks:
cc @DhairyaLGandhi @CarloLucibello @mcabbott @ToucheSir

Move all optimizers to Optimisers.jl

---

src/interface.jl
src/rules.jl
test/runtests.jl

In response to [this discussion](https://github.com/FluxML/ML-Coordination-Tracker/discussions/22#discussioncomment-342967), this PR makes a simple change to the order of the arguments in our interface. Functionally, no changes are made.
Higher-order optimizers (e.g. AdaHessian) consume the first and second derivatives as arguments to the rule. This change allows us to support arbitrary number of derivative terms in the future (though it is limited to only the gradient for now).
Summary of changes:
- `apply(o, x, dx, st)` -> `apply(o, st, x, dx)`
- `update(o, x, dx, st)` -> `update(o, st, x, dx)`
- `o(x, dx, st)` -> `o(st, x, dx)`
The idea is that a future second-order rule would define `apply(o, st, x, grad, hessian) = ...`. And the `update` would be changed to support `Vararg`:
```julia …
```

RFC: Switch interface for higher-order optimizers

---

docs/src/api.md
docs/src/index.md
src/Optimisers.jl
src/interface.jl
src/rules.jl
test/runtests.jl

As discussed here https://github.com/FluxML/Optimisers.jl/pull/29#discussion_r793256133, this removes the need to explicitly pass the optimiser itself, by wrapping it up with the state. Then `Optimisers.update` takes 3 arguments by default, not 4.

Wrap optimiser and state in a struct

---

docs/src/api.md
src/interface.jl
test/runtests.jl

Closes #35.
Should allow you to specify a NamedTuple with any subset of `children(x)`'s names, or a tuple like Flux uses. I hope that Flux could simply import this & things would work.
Otherwise minimal, does not make a `trainable_walk` or change too much else.

Add `trainable`

---

Project.toml
src/rules.jl
test/rules.jl
test/runtests.jl

Testing with StaticArrays exposes some bugs (?) in how this handles element type:
* ~~Some `OptimiserChain` combinations promote to Float64.~~ when they have explicit Float64 parameters
* Most optimisers promote Float16, as their default parameters are Float32.
The PR also divides the tests into two files, one of which has loops over all optimisers, the other tries to test that the framework is doing what it should do.
Many of the optimiser convergence tests simply mark broken all that fail to converge. It's possible that some of these are real bugs. I'm surprised that minimising `sum(abs2, x + x')` isn't easy for all of them.

Add some tests using StaticArrays

---

.github/workflows/ci.yml

I don't think anything here is OS dependent. And 10 tests means they get stuck behind each other in the queue.

Stop testing on windows + mac

---

Project.toml
src/interface.jl
test/runtests.jl

This is a fairly minimal change to allow use with e.g. Diffractor. It just converts all Tangents back to NamedTuples.
It replaces some `all(isnothing)` with dispatch, as this seems a little tidier. (Instead of writing a new `isZero`, to allow also CRC's zero types.)
~~Needs tests.~~ Has a few tests. I tried some more complicated ones with Diffractor, but that's not registered. More later?
Closes #32

Allow types from ChainRules

---

docs/src/api.md
src/interface.jl
src/rules.jl
test/rules.jl
test/runtests.jl

This changes the behaviour of `@.. x = rhs` on immutable objects, to attach the label to the new result. While this may mean that the type of `x` changes, it also fixes several bugs where later lines assumed that `x` would be the new one. Should have noticed this on the first pass, sorry. (This was added in #31.)
There are more subtle ways for things to go wrong. Flux's implementation of OADAM uses the mutable gradient array as the place to save an intermediate step: 
https://github.com/FluxML/Flux.jl/blob/05a608b3fb540661bf68c339793cd7083e2ad400/src/optimise/optimisers.jl#L311-L326
That won't work if `Δ == dx` is immutable, but attaching the label to the RHS also won't work, if that gets mutated in the next step. And in general mutating the gradient is unsafe, if could also be someone …

Separate `@lazy` from `@..` macro, fix some bugs

---

src/interface.jl
test/runtests.jl

Produces this:
```julia
julia> m = (x = [1.0, 2.0], y = sin);
julia> sm = Optimisers.setup(Descent(), m);
julia> Optimisers.update(sm, m)
ERROR: MethodError: no method matching apply!(::Descent{Float32}, ::Nothing, ::Vector{Float64})
```
vs. before, silently doing nothing:
```julia
julia> Optimisers.update(sm, m)
((x = Leaf(Descent{Float32}(0.1), nothing), y = nothing), (x = [1.0, 2.0], y = sin))
```

Ensure that `update` without a gradient is an error

---

src/rules.jl
test/rules.jl

This copies https://github.com/FluxML/Flux.jl/pull/1776 ~~but doesn't work. Why?~~
Xref #38
Edit: ~~Now this is on top of #48.~~ The original tests pass, but ADADelta only just passes, only the last few digits of the loss decrease. ~~Not sure if~~ That's true in Flux too. ~~Might be a bug somewhere?~~ Because the parameters chosen are strange ones.

Complex numbers alla Flux 1776

---

src/Optimisers.jl
src/interface.jl
src/rules.jl
test/rules.jl
test/runtests.jl

Closes #55
This now rejects arrays of integers as not being things to optimise. Previously, they were, but most optimisers will promote to a float, and `update!` then didn't write in-place, and returned arrays of floats on the first run. I start to think it's cleaner just to declare that `Vector{Int}` cannot be trained.

Explicitly preserve eltype

---

Project.toml
docs/src/api.md
src/Optimisers.jl
src/destructure.jl
src/interface.jl
test/destructure.jl
test/rules.jl
test/runtests.jl

This adds a `destructure` function, like Flux's, which should handle awkward cases. Reqiures https://github.com/FluxML/Functors.jl/pull/37 . 
Alternative to #40 . This seems like a tidier approach, although not quite as short and elegant as it was before I started adding tests. The key idea is that, on the first walk over the model to flatten it, you can make a tree of vector offsets, which simplifies the reconstruction step and the gradients. The gradient of reconstruction isn't an `fmap` walk, but because it already knows the offsets, it does not care if the walks' orders don't match. 
Should work with numbers too if `isnumeric` is widened to allow them. Should work with mixed element types too, promote for the vector, project back for the reconstruction.
The reason to put it here not …

Add `destructure`, take II

---

Project.toml
src/destructure.jl
test/destructure.jl

Bug found in https://github.com/FluxML/Flux.jl/pull/1901

Missing `vec` in gradient of `destructure`

---

Project.toml
src/rules.jl

This adds some comments borrowed from Flux in from #46, whose main change we decided wasn't needed.

Improve `WeightDecay` docstring

---

src/destructure.jl
test/destructure.jl

Fixes a bug discovered in https://github.com/SciML/DiffEqFlux.jl/pull/699, that the adjoint of `re` has to allow for (some of) the leaves having a wider type than the original vector.
This approach costs a copy when this happens, but is much simpler than trying to walk the tree and infer the eltype before starting.

Widen in `_grad!`

---

Project.toml
README.md
src/Optimisers.jl
src/rules.jl
test/rules.jl
test/runtests.jl

I don't know where this package (and Flux) got the all-capital ADAM from, but the paper calls it Adam. It also has seemingly arbitrary pairs like "ADAGrad, AdaMax". So this PR proposes to standardise on Julia-like capitalisations. 
The old ones are marked `@deprecate` which is noisy only in tests, and should still export them. 
The tests are for now untouched.
Xref https://github.com/FluxML/Flux.jl/issues/1949

Replace ADAM with Adam etc

---

Project.toml
src/rules.jl
test/rules.jl

Parallel to https://github.com/FluxML/Flux.jl/pull/1778. 
But if "Parameters other than learning rate generally don't need tuning", then having to type them out to get to the boolean one seems awkward. Cleaner to call it a new optimiser?

Centred RMSProp

---

docs/src/api.md

Deprecations introduced in #78 broke the docstrings for these optimisers. This fixes those

Fix docstrings broken by deprecations

---

docs/src/index.md

Continues the expansion of the main doc page from #80, to explain `destructure` a bit, since that's the other main feature of this package.

Add doc section about `destructure`

---

src/Optimisers.jl

Extend `setup` docstring to show custom struct

---

src/destructure.jl

This adds a note to explain that `destructure` promotes eltypes, and (usually) reverses such promotion on reconstruction, to match the original model.

Expand `destructure`'s docstring a little

---

src/Optimisers.jl

The `update!` docstring ends with the warning  "However, you should not rely on the old model being fully updated." which maybe is a little unclear and vague. 
I updated a bit the docstring and added an example. We could explain in which situation the old model won't be updated (scalar fields in a mutable struct?) if a simple explanation is available.

add an example to update!

---

docs/src/api.md
docs/src/index.md
src/Optimisers.jl
src/adjust.jl
src/interface.jl
src/rules.jl
test/runtests.jl

Closes #88, by adding making `setup(Adam(), state)` and `setup(0.02, state)` re-build the state tree with different parameters. This would have been trivial before #30 changed `update!(o, state, x, x̄)` to `update!(tree, x, x̄)`.
Right now the new `adjust` is like `init`, acts on one thing, while `setup` & `update` act on the whole model/tree. Could avoid the name by making them callable, like `Adam()(0.02)`, which perhaps some earlier version had. 
At the moment many things are errors, such as mismatched optimisers, and rules without a field `:eta` to change. It's possible that they should instead do nothing, so that only some leaves are changed, others left alone.
Could easily be generalised to say `setup(state; eta=0.02)` allowing you to set any field of all rules. If desired.

Add `adjust`

---

.gitignore
src/interface.jl
test/runtests.jl

This adds some tests that should have been added as part of #16. I actually caught a bug and had to fix it.
I have intentionally did not update the documentation. For anyone reading this PR: *higher order optimizers are still not supported.* The only purpose here is make sure we could support them in theory at the interface level. The tests added only ensure that the basic behavior based on this works. There are still no higher order rules.

Add tests for higher order interface

---

Project.toml
docs/src/index.md
src/Optimisers.jl
src/adjust.jl
src/interface.jl
test/runtests.jl

Another take on #100. Borrows the idea of making `Leaf` mutable.
~~Tries~~Tried to be simpler by pushing more of the recursion onto `fmap`:
* `setup` is just `fmapstructure` really. Its notion of sharing is thus exactly the one of Functors, one source of truth. We should fix that not to share `isbits` types, eventually.
* `update!` is just `fmap`. Much of the complication of the old walk was to reconstruct both the state and the model on the way out. But this isn't needed if Leaf is mutated. 
Tests from #100 pass with first commit. However, the shared Leaves must always match shared Arrays. It's possible that this scenario can be done even more simply, possibly without mutable Leaf. 
What #100 does is instead to take shared Leaves as the truth about parameter sharing, which some future …

Allow shared parameters, take III

---

docs/src/api.md
docs/src/index.md
src/adjust.jl
src/interface.jl
test/runtests.jl

Replaces #49 with something much simpler: now that `Leaf` is mutable, you can simply pass it the appropriate limb of the state tree, rather than having some explicit address mechanism.
Addresses some of #107

Add `freeze!`/`thaw!`

---

docs/src/api.md

Seems this paragraph wants to have docs for `trainable` just below it.

Simple docs change

---

docs/src/api.md
docs/src/index.md
src/adjust.jl
test/runtests.jl

Now that `Leaf` is mutable, perhaps it is useful to be able to change `eta` only for some parts of the model.
PR also solves the following bug: `adjust` doesn't copy the momenta, and thus they remain shared with the previous object.

Add `adjust!`

---

src/adjust.jl
src/rules.jl

I noticed that `OptimiserChain` was not marked `@functor`; this PR marks it as such to allow one to modify the rules internal to `OptimiserChain` via `fmap`.
I also modified the optimiser chain state to be a `Tuple` instead of an `AbstractArray` for better type inference in `apply!(o::OptimiserChain, ...)`. If this is considered breaking/undesired I can remove it from the PR. Example of the improved inference:
```julia
x = zeros(Float32, 3)
dx = zero(x)
rule = AdamW()
state = Optimisers.setup(rule, x)
@code_warntype Optimisers.apply!(rule, state.state, x, dx)
```
Before:
```julia
MethodInstance for Optimisers.apply!(::OptimiserChain{Tuple{Adam{Float32}, WeightDecay{Float32}}}, ::Vector{Union{Nothing, Tuple{Vector{Float32}, Vector{Float32}, Tuple{Float32, Float32}}}}, ::Vector{Float32}, …
```

Mark `OptimiserChain` as `@functor` and improve inference for `apply!`

---

Project.toml
docs/src/index.md
test/destructure.jl
test/rules.jl
test/runtests.jl

Does not close https://github.com/FluxML/Optimisers.jl/issues/96, in fact this surely makes tests slower. But perhaps it's good to get something besides Zygote running?

Test with Yota, too

---

src/interface.jl

This rarely needs to be overloaded. Maybe its docstring should say so, a bit more strongly.

Discourage use of `trainable`

---

src/Optimisers.jl
src/rules.jl
test/rules.jl

Implementation of Lion optimiser which is faster than AdamW from [Symbolic Discovery of Optimization Algorithms](https://arxiv.org/abs/2302.06675)

Add implementation of Lion optimiser

---

Project.toml

`AbstractWalk` was introduced in Functors@0.4.0 (https://github.com/FluxML/Functors.jl/blob/v0.4.0/src/walks.jl)

fix: rm Functors@0.3

---

src/Optimisers.jl
src/adjust.jl
src/interface.jl
src/rules.jl
src/utils.jl
test/rules.jl
test/runtests.jl

Rule for gradient accumulation

---

docs/src/index.md
src/Optimisers.jl

Doc-only change. 
We use `state` for what `init` returns, so should probably never use it for what `setup` returns. That's called `tree` in code, and this calls it `state_tree` more places in the docs.
Unsure if we should change headings like `Optimisers.update!(tree, model, gradient) -> (tree, model)` to the more verbose `Optimisers.update!(state_tree, model, gradient) -> (state_tree, model)`.
Another possibility for docs is to call the whole thing `states` plural.

Don't use `state` anywhere for the whole state tree

---

.github/workflows/TagBot.yml

This may also finally allow us to deploy docs for tagged versions, if I'm reading https://github.com/FluxML/Functors.jl/pull/18 correctly.

Update TagBot config

---

Project.toml
src/rules.jl
test/runtests.jl

Make ClipNorm work on GPU Broadcasted

---

Project.toml
src/Optimisers.jl
src/rules.jl
test/rules.jl
test/runtests.jl

As I learned here https://github.com/FluxML/MLJFlux.jl/issues/221#issuecomment-1707604760 , since the gradient of L1 norm is even simpler than the gradient of L2 norm it can, obviously, be implemented as an optimisation rule.
This quick PR adds it to the same WeightDecay struct. Below is a check that this does what you expect.
<details>
```julia
using Flux: Flux, Dense, gradient, state
using Optimisers
using Optimisers: setup, update
input = [1,2]
model = Dense([1 -2; 3 -4.0])
grads = Flux.gradient(model) do m
result = m(input)
sum(result)
end
pen_l2(x::AbstractArray) = sum(abs2, x)/2
grads_L2 = Flux.gradient(model) do m
result = m(input)
penalty = sum(pen_l2, Flux.params(m))
sum(result) + 0.42 * penalty
end
update(
setup(Descent(0.1), model),
model, grads_L2[1])[2] |> Flux.state
update( …
```

WeightDecay for L1 norm

---

src/interface.jl
src/rules.jl
test/runtests.jl

Allows this:
```julia
julia> AdamW(lambda=333e-3)
OptimiserChain(Adam(0.001, (0.9, 0.999), 1.0e-8), WeightDecay(0.333))
```
Not entirely sure it's worth the complexity & extra documentation.
(Note that `adjust!` already exposes field names, so in a sense they are already API.)

Add all-keyword constructors, much like `@kwdef`

---

docs/src/api.md
docs/src/index.md
src/Optimisers.jl
src/destructure.jl
src/interface.jl
src/trainables.jl
test/runtests.jl
test/trainables.jl

An alternative to #57 adding the `trainables` method that returns a vector of arrays. 
I'm playing with different implementations at the moment. The output of the `perf()` function is 
```
trainables1
1.717 μs (33 allocations: 1.48 KiB)
trainables2
2.708 μs (63 allocations: 3.12 KiB)
trainables3
11.208 μs (147 allocations: 4.39 KiB)
gradient trainables2
1.546 ms (7157 allocations: 304.39 KiB)
gradient trainables3
249.625 μs (2289 allocations: 115.39 KiB)
```
`trainables1` is the fastest but since it is mutating it needs a custom `rrule` for differentiation. Probably the rrule for `destructor` can be adapted for this case
https://github.com/FluxML/Optimisers.jl/blob/master/src/destructure.jl
The gradients of the other two implementations are very slow, also in these cases we would need a …

add `trainables`

---

src/interface.jl

Add indent on docstring's signature of the `@def` macro so that Julia's documentation system picks it up. Also adds language tag for expanded macro code.

Fix macro signature in docstring

---

Project.toml
README.md
src/rules.jl
test/rules.jl
test/runtests.jl

See https://github.com/FluxML/Flux.jl/issues/2433 for the details
Close https://github.com/FluxML/Flux.jl/issues/2433

Add the option couple to AdamW and set the default to match pytorch

---

.github/workflows/ci.yml
Project.toml
docs/src/index.md
ext/OptimisersEnzymeCoreExt.jl
test/runtests.jl

This moves part of https://github.com/FluxML/Flux.jl/pull/2471 to an extension here. 
Bumps Julia support to 1.10.

Add `Duplicated` methods

---

src/rules.jl

As per comment https://github.com/FluxML/Optimisers.jl/pull/198#discussion_r1880405919,
since we do it for any other rule (explicitly or through `@def`) except for `Descent`.
Is there any reason why `Descent` is left out @mcabbott ?

restrict AdamW's fields to Float64 

---

docs/src/index.md
src/destructure.jl
src/trainables.jl

- Add about section to main documentation page (from README.md)
- Add installation section to main documentation page (from README.md)
- Update language tags for REPL examples
- Update spacing for REPL examples

Update doc pages and docstrings

---

Project.toml
ext/OptimisersReactantExt.jl

Add extension to prevent stackoverflow when using Reactant.
Origin of bug in https://github.com/FluxML/Fluxperimental.jl/pull/28
```
simple train!: Error During Test at /Users/wmoses/git/Fluxperimental.jl/test/reactant.jl:152
Got exception outside of a @test
StackOverflowError:
Stacktrace:
[1] mlirOperationCreate
@ ~/git/Reactant.jl/src/mlir/libMLIR_h.jl:1005 [inlined]
[2] create_operation(name::String, loc::Reactant.MLIR.IR.Location; results::Vector{Reactant.MLIR.IR.Type}, operands::Vector{Reactant.MLIR.IR.Value}, owned_regions::Vector{Reactant.MLIR.IR.Region}, successors::Vector{Reactant.MLIR.IR.Block}, attributes::Vector{Reactant.MLIR.IR.NamedAttribute}, result_inference::Bool)
@ Reactant.MLIR.IR ~/git/Reactant.jl/src/mlir/IR/Operation.jl:319
[3] constant(; …
```

Reactant: add extension to prevent stackoverflow
